# Generated by Django 3.2.5 on 2021-08-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
